"""initial_schema

Revision ID: 640531ae70ee
Revises: 
Create Date: 2026-05-10 20:07:43.091369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '640531ae70ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('police_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('jurisdiction', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_police_stations_id'), 'police_stations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnic', sa.String(length=15), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('citizen', 'admin', 'officer', name='userrole'), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('badge_number', sa.String(length=50), nullable=True),
    sa.Column('rank', sa.String(length=50), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['police_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cnic'), 'users', ['cnic'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('fcm_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('device_info', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_fcm_tokens_id'), 'fcm_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_fcm_tokens_user_id'), 'fcm_tokens', ['user_id'], unique=False)
    op.create_table('firs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('incident_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('incident_location', sa.String(length=500), nullable=True),
    sa.Column('category', sa.Enum('theft', 'assault', 'fraud', 'cybercrime', 'harassment', 'robbery', 'murder', 'kidnapping', 'domestic_violence', 'other', name='fircategory'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='firpriority'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'under_investigation', 'resolved', 'closed', name='firstatus'), nullable=False),
    sa.Column('assigned_officer_id', sa.Integer(), nullable=True),
    sa.Column('officer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firs_assigned_officer_id'), 'firs', ['assigned_officer_id'], unique=False)
    op.create_index(op.f('ix_firs_id'), 'firs', ['id'], unique=False)
    op.create_index(op.f('ix_firs_status'), 'firs', ['status'], unique=False)
    op.create_index(op.f('ix_firs_tracking_number'), 'firs', ['tracking_number'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('notification_type', sa.Enum('fir_status_update', 'fir_assigned', 'fir_comment', 'account_update', 'general', name='notificationtype'), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fir_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fir_id'], ['firs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_fir_id'), 'evidence', ['fir_id'], unique=False)
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_table('fir_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fir_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fir_id'], ['firs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fir_comments_fir_id'), 'fir_comments', ['fir_id'], unique=False)
    op.create_index(op.f('ix_fir_comments_id'), 'fir_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fir_comments_id'), table_name='fir_comments')
    op.drop_index(op.f('ix_fir_comments_fir_id'), table_name='fir_comments')
    op.drop_table('fir_comments')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_fir_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_firs_tracking_number'), table_name='firs')
    op.drop_index(op.f('ix_firs_status'), table_name='firs')
    op.drop_index(op.f('ix_firs_id'), table_name='firs')
    op.drop_index(op.f('ix_firs_assigned_officer_id'), table_name='firs')
    op.drop_table('firs')
    op.drop_index(op.f('ix_fcm_tokens_user_id'), table_name='fcm_tokens')
    op.drop_index(op.f('ix_fcm_tokens_id'), table_name='fcm_tokens')
    op.drop_table('fcm_tokens')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cnic'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_police_stations_id'), table_name='police_stations')
    op.drop_table('police_stations')
    # ### end Alembic commands ###
