"""expand_models_v2

Revision ID: d7d68ce197e9
Revises: 9a89a762a577
Create Date: 2026-05-07 00:35:02.966746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7d68ce197e9'
down_revision: Union[str, None] = '9a89a762a577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('police_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('jurisdiction', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_police_stations_id'), 'police_stations', ['id'], unique=False)
    op.create_table('fcm_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('device_info', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_fcm_tokens_id'), 'fcm_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_fcm_tokens_user_id'), 'fcm_tokens', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('notification_type', sa.Enum('fir_status_update', 'fir_assigned', 'fir_comment', 'account_update', 'general', name='notificationtype'), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fir_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fir_id'], ['firs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_fir_id'), 'evidence', ['fir_id'], unique=False)
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_table('fir_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fir_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fir_id'], ['firs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fir_comments_fir_id'), 'fir_comments', ['fir_id'], unique=False)
    op.create_index(op.f('ix_fir_comments_id'), 'fir_comments', ['id'], unique=False)
    # Create enum types first
    fircategory = sa.Enum('theft', 'assault', 'fraud', 'cybercrime', 'harassment', 'robbery', 'murder', 'kidnapping', 'domestic_violence', 'other', name='fircategory')
    fircategory.create(op.get_bind(), checkfirst=True)
    firpriority = sa.Enum('low', 'medium', 'high', 'critical', name='firpriority')
    firpriority.create(op.get_bind(), checkfirst=True)

    # Add columns with server_default for existing rows
    op.add_column('firs', sa.Column('title', sa.String(length=200), nullable=False, server_default='Untitled FIR'))
    op.add_column('firs', sa.Column('incident_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('firs', sa.Column('incident_location', sa.String(length=500), nullable=True))
    op.add_column('firs', sa.Column('category', fircategory, nullable=False, server_default='other'))
    op.add_column('firs', sa.Column('priority', firpriority, nullable=False, server_default='medium'))
    op.add_column('firs', sa.Column('officer_notes', sa.Text(), nullable=True))
    op.add_column('firs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('firs', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_firs_assigned_officer_id'), 'firs', ['assigned_officer_id'], unique=False)
    op.create_index(op.f('ix_firs_status'), 'firs', ['status'], unique=False)
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('users', sa.Column('badge_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('rank', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('station_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_foreign_key(None, 'users', 'police_stations', ['station_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'station_id')
    op.drop_column('users', 'rank')
    op.drop_column('users', 'badge_number')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'address')
    op.drop_column('users', 'email')
    op.drop_index(op.f('ix_firs_status'), table_name='firs')
    op.drop_index(op.f('ix_firs_assigned_officer_id'), table_name='firs')
    op.alter_column('firs', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('firs', 'updated_at')
    op.drop_column('firs', 'officer_notes')
    op.drop_column('firs', 'priority')
    op.drop_column('firs', 'category')
    op.drop_column('firs', 'incident_location')
    op.drop_column('firs', 'incident_date')
    op.drop_column('firs', 'title')
    op.drop_index(op.f('ix_fir_comments_id'), table_name='fir_comments')
    op.drop_index(op.f('ix_fir_comments_fir_id'), table_name='fir_comments')
    op.drop_table('fir_comments')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_fir_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_fcm_tokens_user_id'), table_name='fcm_tokens')
    op.drop_index(op.f('ix_fcm_tokens_id'), table_name='fcm_tokens')
    op.drop_table('fcm_tokens')
    op.drop_index(op.f('ix_police_stations_id'), table_name='police_stations')
    op.drop_table('police_stations')
    # ### end Alembic commands ###
